export const UI_STRINGS = {
  common: {
    appTitle: 'نقش‌نما',
    shortTitle: 'نقش‌نما',
    subtitle: 'تصویری از شیوه نقش‌آفرینی شما در تیم',
    versionBadge: 'نسخه ۱.۰',
    syncing: 'در حال ذخیره‌سازی ابری…',
    synced: 'ذخیره شد',
    offline: 'ارتباط آفلاین است — پیشرفت محلی نگهداری می‌شود',
    next: 'مرحله بعد',
    prev: 'مرحله قبل',
    continue: 'ادامه',
    confirm: 'تأیید و ثبت',
    cancel: 'انصراف',
    retry: 'تلاش دوباره',
    close: 'بستن',
    save: 'ذخیره',
    copy: 'کپی',
    copied: 'کپی شد!',
    downloadPdf: 'دانلود گزارش PDF',
    downloadImage: 'ذخیره به عنوان تصویر',
    copyTracking: 'کپی کد پیگیری و لینک',
    restart: 'شروع ارزیابی جدید',
    adminLogin: 'ورود به پنل مدیریت',
    backToApp: 'بازگشت به ارزیابی',
    themeLight: 'حالت روشن',
    themeDark: 'حالت تیره',
    themeSystem: 'پیروی از سیستم',
    loading: 'در حال بارگذاری…',
  },
  login: {
    title: 'ورود به نقش‌نما',
    subtitle: 'نام کاربری شما شمارهٔ همراه و رمز عبور شما کد ملی است. حساب‌ها توسط مدیر سامانه تعریف می‌شوند.',
    phone: 'شمارهٔ همراه (نام کاربری)',
    phonePlaceholder: '۰۹۱۲۳۴۵۶۷۸۹',
    phoneError: 'شمارهٔ همراه معتبر نیست (مثال: ۰۹۱۲۳۴۵۶۷۸۹)',
    nationalId: 'کد ملی (رمز عبور)',
    nationalIdPlaceholder: '۱۰ رقم',
    nationalIdHint: 'کد ملی ۱۰ رقمی بدون خط تیره',
    nationalIdError: 'کد ملی معتبر نیست',
    show: 'نمایش رمز',
    hide: 'پنهان کردن رمز',
    submit: 'ورود',
    invalidCredentials: 'شمارهٔ همراه یا کد ملی نادرست است یا برای شما حسابی تعریف نشده است.',
    locked: 'به دلیل تلاش‌های ناموفق متعدد، ورود تا ۱۵ دقیقه مسدود شد.',
    network: 'اتصال به سرور برقرار نشد. اینترنت خود را بررسی کنید و دوباره تلاش کنید.',
    server: 'خطایی در سرور رخ داد. کمی بعد دوباره تلاش کنید.',
    welcome: 'خوش آمدید',
    loggedInAs: 'وارد شده با شماره',
    logout: 'خروج',
    previousResultTitle: 'نتیجهٔ ارزیابی قبلی شما آماده است',
    previousResultDesc: 'می‌توانید گزارش قبلی را ببینید یا ارزیابی جدیدی را شروع کنید.',
    viewPreviousResult: 'مشاهده گزارش قبلی',
  },
  start: {
    badge: 'شناخت الگوهای رفتار تیمی',
    title: 'نقش‌نما',
    frameworkNote: '«تصویری از شیوه نقش‌آفرینی شما در تیم»',
    description: 'چند موقعیت کاری و انتخاب ساده. جواب درست یا غلط وجود ندارد؛ آنچه را که معمولاً بیشتر به شما نزدیک است انتخاب کنید.',
    timeEstimateTitle: 'زمان تقریبی',
    timeEstimateDesc: 'حدود ۱۰ تا ۱۵ دقیقه زمان متمرکز و بدون شتاب',
    natureTitle: 'ماهیت ارزیابی',
    natureDesc: 'این ابزار یک ارزیابی رفتاری است و تست استاندارد یا قضاوت ارزشی به شمار نمی‌رود.',
    stepsOverviewTitle: 'مراحل ارزیابی:',
    step1: 'بخش اول: ۱۸ مقایسه زوجی رویکردها (انتخاب ترجیح)',
    step2: 'بخش دوم: ۹ سناریوی کاری با انتخاب اولویت اول و دوم',
    step3: 'بخش سوم: ۳ مینی‌گیم اولویت‌بندی فعالیت‌ها در پروژه‌ها',
    formHeader: 'مشخصات شرکت‌کننده',
    firstName: 'نام',
    firstNamePlaceholder: 'مثال: سارا',
    lastName: 'نام خانوادگی',
    lastNamePlaceholder: 'مثال: محمدی',
    mobile: 'شماره همراه',
    mobilePlaceholder: '۰۹۱۲۳۴۵۶۷۸۹',
    mobileHint: 'برای دریافت نسخه گزارش در پنل سازمان یا بازیابی بعدی',
    mobileError: 'شماره تلفن همراه معتبر نیست (مثال: ۰۹۱۲۳۴۵۶۷۸۹)',
    orgCode: 'کد سازمان / تیم (اختیاری)',
    orgCodePlaceholder: 'مثال: ACME-TEAM',
    privacyNote: 'یادداشت محرمانگی: اطلاعات و نتایج شما صرفاً برای بازتاب و خودآگاهی تیمی است و به عنوان برچسب قطعی یا ملاک صلاحیت شغلی تلقی نمی‌شود.',
    startButton: 'شروع ارزیابی',
    continueButton: 'ادامه ارزیابی ناتمام',
    resumeAlertTitle: 'ارزیابی قبلی ذخیره شده است',
    resumeAlertDesc: 'یک جلسه ناتمام در این دستگاه یافت شد. مایلید از همان مرحله ادامه دهید؟',
    startNew: 'شروع از ابتدا',
  },
  sectionA: {
    sectionTag: 'بخش اول • مقایسه دو رویکرد',
    prompt: 'کدام رویکرد معمولاً بیشتر به شما نزدیک‌تر است؟',
    placeholderTitle: 'تصویر مفهومی',
    shortcutHint: 'کلیدهای ۱ تا ۴ کیبورد برای انتخاب سریع',
    optionEntirelyFirst: 'کاملاً این',
    optionPartiallyFirst: 'کمی این',
    optionPartiallySecond: 'کمی این',
    optionEntirelySecond: 'کاملاً این',
    card1Badge: 'کارت اول',
    card2Badge: 'کارت دوم',
  },
  break: {
    badge: 'استراحت کوتاه بصری',
    title: 'بخش بعد: چند موقعیت واقعی کاری',
    description: 'در بخش دوم، ۹ سناریوی ملموس کاری را مرور خواهید کرد. در هر سناریو، دو اقدام نخست خود را انتخاب خواهید نمود.',
    breathHint: 'یک نفس آرام بکشید…',
    continueButton: 'ورود به سناریوهای کاری',
    progressNotice: '۱۸ مورد از رویکردها تکمیل شد.',
  },
  sectionB: {
    sectionTag: 'بخش دوم • سناریوهای موقعیتی',
    stage1Instruction: 'مرحله ۱: اقدامی که احتمالاً اول انجام می‌دهید را انتخاب کنید.',
    stage2Instruction: 'مرحله ۲: از بین گزینه‌های باقیمانده، اقدام دوم را انتخاب کنید.',
    completedInstruction: 'هر دو اقدام مشخص شدند. آماده ثبت نهایی.',
    resetChoices: 'تغییر انتخاب‌ها',
    firstChoiceBadge: 'اول',
    secondChoiceBadge: 'دوم',
    submitButton: 'تأیید و سناریوی بعدی',
  },
  sectionC: {
    sectionTag: 'بخش سوم • اولویت‌بندی در عمل',
    pickInstruction: 'سه اقدام را به ترتیب اولویت (اول، دوم، سوم) انتخاب کنید.',
    remainingInstruction: (n: string) => `${n} اقدام دیگر را برای اولویت‌بندی انتخاب کنید.`,
    completedInstruction: 'سه اقدام منتخب رتبه‌بندی شدند.',
    rank1: '۱',
    rank2: '۲',
    rank3: '۳',
    moveUp: 'انتقال به بالا',
    moveDown: 'انتقال به پایین',
    resetGame: 'شروع مجدد این مینی‌گیم',
    submitToNext: 'ثبت و رفتن به بخش بعدی',
    submitToReview: 'ثبت و بررسی پایانی',
  },
  review: {
    badge: 'بررسی پیش از نهایی‌سازی',
    title: 'ارزیابی شما آماده نهایی‌سازی است',
    description: 'تمامی ۳۰ مرحله ارزیابی با موفقیت تکمیل شده‌اند. بر اساس اصول روان‌سنجی ابزار، پاسخ‌های ثبت‌شده غیرقابل بازگشت هستند تا الگوهای پاسخ دچار سوگیری ثانویه نشوند.',
    checklistA: '۱۸ مقایسه رویکرد زوجی ثبت شد.',
    checklistB: '۹ سناریوی موقعیتی با دو اولویت ثبت شد.',
    checklistC: '۳ مینی‌گیم اولویت‌بندی پروژه‌ای رتبه‌بندی شد.',
    timeTaken: 'زمان کل سپری شده:',
    confirmAndReveal: 'مشاهده و کشف پروفایل تیمی',
  },
  reveal: {
    title: 'در حال تحلیل الگوهای تیمی…',
    subtitle: 'ترکیب محاسبات FC ،SJT و GAME بر مبنای ۹ نقش تیمی',
    skip: 'رد شدن از انیمیشن',
  },
  report: {
    tag: 'گزارش رسمی بازتاب رفتاری',
    title: 'نتیجه ارزیابی نقش‌های تیمی',
    participantPrefix: 'برای',
    trackingCodeLabel: 'کد پیگیری:',
    dateLabel: 'تاریخ ارزیابی:',
    top3Title: 'نقش‌های با بیشترین گرایش طبیعی (۳ نقش ترجیحی)',
    top3Subtitle: 'نقش‌هایی که در محیط تیمی بیشترین خودانگیختگی و تمایل را برای ایفای آن‌ها نشان داده‌اید.',
    all9Title: 'پروفایل توزیع هر ۹ نقش تیمی',
    all9Subtitle: 'ترتیب نزولی گرایش‌ها بر پایه امتیاز نهایی (۰ تا ۱۰۰)',
    chartTabHorizontal: 'نمودار میله‌ای',
    chartTabRadar: 'نمودار رادار توازن',
    radarTitle: 'نمودار رادار توازن ۹ نقش تیمی',
    cardFlipHint: 'برای مشاهده رفتارهای قابل مشاهده، نقاط کور و شرایط اثربخشی، روی هر کارت کلیک کنید (چرخش کارت)',
    detailsTitle: 'تحلیل تفصیلی نقش‌ها (چرخش کارت)',
    closeGapBadge: 'تقریباً هم‌سطح',
    closeGapNote: 'فاصله امتیاز اندک (≤ ۳ امتیاز)؛ ترتیب نباید بیش از حد تفسیر شود.',
    contributionLabel: 'سهم طبیعی در تیم',
    behaviorsLabel: 'رفتارهای قابل مشاهده',
    blindSpotLabel: 'نقطه کور محتمل',
    conditionsLabel: 'بهترین شرایط استفاده',
    leastTendencyTitle: 'درباره نقش‌های با گرایش طبیعی کمتر (رتبه ۷ تا ۹)',
    leastTendencyDesc: (r1: string, r2: string, r3: string) =>
      `در مقایسه با سایر نقش‌ها، تمایل طبیعی کمتری به ایفای خودجوش نقش‌های ${r1}، ${r2} و ${r3} نشان داده‌اید. این به معنای ناتوانی نیست؛ بلکه نشان می‌دهد این نقش‌ها انرژی اولیه شما را جذب نمی‌کنند و هم‌افزایی با هم‌تیمی‌هایی با این ترجیحات موجب تعادل تیم خواهد شد.`,
    ethicsClosingTitle: 'یادداشت پایانی و اخلاق ارزیابی',
    ethicsClosingText: 'این ارزیابی بر پایه چارچوب نقش‌های تیمی طراحی شده و یک ابزار رفتاری است؛ نتیجه را به‌عنوان نقطه شروع گفت‌وگو ببینید، نه برچسب قطعی.',
  },
  adminUsers: {
    tabResults: 'نتایج ارزیابی‌ها',
    tabUsers: 'کاربران',
    importTitle: 'وارد کردن کاربران از فایل',
    importHint: 'فایل Excel (‎.xlsx) یا CSV با ستون‌های «نام و نام خانوادگی»، «کد ملی» و «شماره تماس». اگر ستون‌ها عنوان نداشته باشند، ترتیب نام، کد ملی، شماره تماس در نظر گرفته می‌شود. صفر ابتدایی حذف‌شده در Excel خودکار بازیابی می‌شود.',
    chooseFile: 'انتخاب فایل',
    downloadTemplate: 'دانلود فایل نمونه',
    parsing: 'در حال خواندن فایل…',
    parseFailed: 'خواندن فایل ممکن نشد. فقط فایل‌های ‎.xlsx و ‎.csv پشتیبانی می‌شوند.',
    emptyFile: 'در فایل هیچ ردیفی پیدا نشد.',
    summaryTotal: 'کل ردیف‌ها',
    summaryValid: 'معتبر',
    summaryInvalid: 'دارای خطا',
    colRow: 'ردیف',
    colName: 'نام',
    colPhone: 'شماره تماس',
    colNid: 'کد ملی',
    colStatus: 'وضعیت',
    colCreated: 'تاریخ ساخت',
    colLastLogin: 'آخرین ورود',
    colSessions: 'ارزیابی‌ها',
    statusOk: 'معتبر',
    reasons: {
      invalid_phone: 'شماره تماس نامعتبر',
      invalid_national_id: 'کد ملی نامعتبر',
      missing_name: 'نام خالی است',
      duplicate_phone: 'شماره تکراری در فایل',
      duplicate_national_id: 'کد ملی تکراری در فایل',
    } as Record<string, string>,
    previewNote: 'فقط ۵۰ ردیف اول نمایش داده می‌شود.',
    importButton: 'ثبت کاربران معتبر',
    importing: 'در حال ثبت…',
    importDone: 'ثبت انجام شد',
    created: 'جدید',
    updated: 'به‌روزرسانی‌شده',
    failed: 'ناموفق',
    updateNote: 'اگر شماره‌ای از قبل وجود داشته باشد، نام و کد ملی آن با اطلاعات فایل جایگزین می‌شود.',
    backendUnavailable: 'سرور در دسترس نیست. مدیریت کاربران فقط روی نسخهٔ منتشرشده (Vercel + Neon) کار می‌کند.',
    listTitle: 'کاربران ثبت‌شده',
    searchPlaceholder: 'جستجو بر اساس نام یا شماره…',
    noUsers: 'هنوز کاربری ثبت نشده است.',
    never: '—',
    delete: 'حذف',
    confirmDelete: 'این کاربر حذف شود؟ نتایج ارزیابی او باقی می‌ماند ولی دیگر نمی‌تواند وارد شود.',
    total: 'تعداد کاربران',
  },
  admin: {
    badge: 'پنل مدیریت و پایش داده',
    title: 'داشبورد کنترل کیفیت و جلسات ارزیابی',
    totalSessions: 'مجموع جلسات:',
    authNotice: 'ورود به پنل مدیریت با رمز تنظیم‌شده روی سرور بررسی می‌شود.',
    passwordNotConfigured: 'رمز مدیریت روی سرور تنظیم نشده است (ADMIN_PASSWORD).',
    localDataNotice: 'سرور در دسترس نیست؛ فقط جلسه‌های همین مرورگر نمایش داده می‌شود.',
    loginTitle: 'ورود به پنل مدیریت',
    loginSubtitle: 'مشاهده آرشیو جلسات، ممیزی RQI و خروجی داده‌ها',
    passwordLabel: 'رمز عبور مدیریت',
    passwordPlaceholder: 'رمز عبور (پیش‌فرض: admin)',
    loginButton: 'ورود به پنل',
    invalidPassword: 'رمز عبور نادرست است.',
    searchPlaceholder: 'جست‌وجوی نام، شماره تماس یا شناسه جلسه…',
    refresh: 'به‌روزرسانی جدول',
    exportCsv: 'خروجی CSV',
    exportJson: 'خروجی JSON',
    runTests: 'تست‌های اعتبارسنجی ابزار',
    tableColName: 'شرکت‌کننده / تماس',
    tableColDate: 'تاریخ',
    tableColVersion: 'نسخه',
    tableColRqi: 'شاخص RQI',
    tableColLevel: 'سطح ثبات',
    tableColTop3: 'سه نقش ترجیحی',
    tableColActions: 'عملیات',
    noSessions: 'هیچ جلسه‌ای یافت نشد.',
    modalTitle: 'پرونده ممیزی ارزیابی',
    modalRqiSection: 'ممیزی شاخص کیفیت پاسخ (RQI)',
    modalWarningNote: 'ناهماهنگی پاسخ‌ها به معنی دروغ‌گویی یا عدم صداقت نیست؛ فقط ثبات الگوی پاسخ را نشان می‌دهد.',
    modalVectorsSection: 'بردارهای امتیازات خام و نرمال‌شده ۹ نقش',
    modalTimingSection: 'خلاصه زمان‌سنجی آیتم‌ها',
  },
  devToolbar: {
    title: 'ابزار توسعه (DevToolbar)',
    jumpTo: 'پرش به مرحله:',
    autoFill: 'تکمیل خودکار پاسخ‌ها و پرش به گزارش',
    toggleOffline: 'شبیه‌سازی آفلاین',
    clearAll: 'پاک‌سازی تمام داده‌های محلی',
  },
  error: {
    title: 'خطایی رخ داده است',
    description: 'متأسفانه اجرای این بخش با مشکل غیرمنتظره روبه‌رو شد. داده‌های پیشرفت شما محفوظ است.',
    tryAgain: 'تلاش دوباره',
  },
} as const;
